### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'poetry'

### ISSUE THREAD

**Issue by irfanmuratgoc** [allient/create-fastapi-project#1]
Hi。when i run create fast preject command i get this  error

**Comment by irfanmuratgoc** [comment]
resovled

**Comment by KittenYang** [comment]
@irfanmuratgoc  same with me, how do you solve it?

**Comment by fm-chen** [comment]
> @irfanmuratgoc same with me, how do you solve it?

I got the same error and fixed it.
You need to install poetry: https://python-poetry.org/docs/#installing-with-the-official-installer
